### ISSUE TITLE
Paper source or data source

### ISSUE THREAD

**Issue by henie5** [julienOlivier3/causalForest#1]
Hello. Thanks for your sharing.
By any chance, might I have your paper source or data source?
Best wishes.

**Comment by julienOlivier3** [comment]
Data source I am not entitled to share. Technical paper source can be found here: https://www.pnas.org/content/113/27/7353.full
Hope that helps.

**Comment by henie5** [comment]
I really appreciate it. Actually I 've read the relevent paper of Prof. Athey; And I 'm working on the GRF code right now.&nbsp;
Your codes really have helped me a lot and thanks for that.&nbsp;


&nbsp;

雷恒  华中科技大学 管理学院
 中国 武汉 珞喻路1037号
 Lei Heng
 The School of Management, Huazhong University of Science and Technology
 No. 1037， Luoyu Road，Wuhan，430074，China



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "julienOlivier3"<notifications@github.com&gt;; 
发送时间: 2021年3月8日(星期一) 晚上8:47
收件人: "julienOlivier3/causalForest"<causalForest@noreply.github.com&gt;; 
抄送: "2844347195"<2844347195@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [julienOlivier3/causalForest] Paper source or data source (#1)





 
Data source I am not entitled to share. Technical paper source can be found here: https://www.pnas.org/content/113/27/7353.full
 Hope that helps.
